title: JugadBase DevDocs
description: Developer Docs for 

baseurl: "/jugadbase"
url: "https://itssitanshu.github.io/"

theme: just-the-docs

plugins:
  - jekyll-feed
  - jekyll-seo-tag

just_the_docs:
  search_enabled: true
  dark_mode: true
  sidebar:
    nav_order:
      - index.md
      - flags.md
